name: Bundle JAR with Maven

on:
  push:
    paths:
      - '**/*.java'
  pull_request:
    paths:
      - '**/*.java'

jobs:
  package:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout latest
        uses: actions/checkout@v5
      - name: Set up JDK 8
        uses: actions/setup-java@v4
        with:
          java-version: 8
          distribution: temurin
          cache: maven
      - name: Build with Maven
        run: mvn --batch-mode package
